---
- name: create webistrano database
  mysql_db: name={{database_name}} state=present encoding=utf8

- name: create webistrano accounts
  mysql_user: name=webistrano host={{item}} password={{webistrano_mysql_password}} priv={{database_name}}.*:ALL state=present
  with_items:
    - 127.0.0.1
    - localhost

- name: clone webistrano repository
  git: repo={{webistrano_repo}} dest={{deploy_dir}}/webistrano


- name: copy webistrano.conf file
  template: src=webistrano.conf dest=/etc/httpd/conf.d/webistrano.conf
  notify: restart httpd


- name: copy webistrano_config.rb file
  template: src=webistrano_config.rb.j2 dest={{deploy_dir}}/webistrano/config/webistrano_config.rb

- name: copy database.yml file
  template: src=database.yml.j2 dest={{deploy_dir}}/webistrano/config/database.yml


- name: install bundler for 1.0.10
  gem: name=bundler version=1.0.10


- name: install bundle gems
  command: bundle install  chdir={{deploy_dir}}/webistrano

- name: setup webistrano
  shell: RAILS_ENV=production bundle exec rake db:migrate chdir={{deploy_dir}}/webistrano
- name: change the permissions of $deploy_dir/webistrano
  command: chown -R apache:apache {{deploy_dir}}/webistrano
