---
- name: install passenger gem
  gem: name=passenger state=present version={{passenger_ver}}

- name: install passenger dependency packages
  yum: name={{item}} state=installed
  with_items:
    - gcc
    - gcc-c++
    - curl-devel
    - openssl-devel
    - zlib-devel
    - httpd-devel

- name: install passenger-install-apache2-module
  shell: /usr/bin/passenger-install-apache2-module --auto creates=/usr/lib/ruby/gems/1.9.1/gems/passenger-{{passenger_ver}}/buildout/apache2/mod_passenger.so
- name: generate passenger.conf file
  shell: /usr/bin/passenger-install-apache2-module --snippet > /etc/httpd/conf.d/passenger.conf
- name: chown passenger module dir 
  shell: chown apache.apache -R /usr/lib/ruby/gems/1.9.1/gems/passenger-{{passenger_ver}}
